"""
Repository interface for Admin entity operations.
"""
from __future__ import annotations
from typing import Protocol, Optional
from app.models.account import Admin


class AdminRepository(Protocol):
    def add(self, admin: Admin) -> Admin: ...
    def get_by_id(self, admin_id: int) -> Optional[Admin]: ...
    def get_by_email(self, email: str) -> Optional[Admin]: ...
    def list(self) -> list[Admin]: ...
    def update(self, admin: Admin) -> Admin: ...
    def delete(self, admin_id: int) -> bool: ...
