"""Repository interface for Location entity operations."""
from __future__ import annotations
from typing import Optional, Protocol

from app.models.location import Location


class LocationRepository(Protocol):
    def add(self, location: Location) -> Location: ...
    def get_by_id(self, location_id: int) -> Optional[Location]: ...
    def list(self) -> list[Location]: ...
    def update(self, location: Location) -> Location: ...
    def delete(self, location_id: int) -> bool: ...
