"""
Repository interface for Metrics entity operations.
"""
from __future__ import annotations
from typing import Protocol, Optional
from app.models.metrics import Metrics, DrivingMetrics, PTMetrics, WalkingMetrics, CyclingMetrics


class MetricsRepository(Protocol):
    def add(self, metrics: Metrics) -> Metrics: ...
    def get_by_id(self, metrics_id: int) -> Optional[Metrics]: ...
    def get_by_route_id(self, route_id: int) -> Optional[Metrics]: ...
    def list(self) -> list[Metrics]: ...
    def update(self, metrics: Metrics) -> Metrics: ...
    def delete(self, metrics_id: int) -> bool: ...
