"""
Repository interfaces for Parking-related entities.
"""
from __future__ import annotations
from typing import Protocol, Optional
from app.models.parking import Carpark, BikeSharingPoint


class CarparkRepository(Protocol):
    def add(self, carpark: Carpark) -> Carpark: ...
    def get_by_id(self, carpark_id: int) -> Optional[Carpark]: ...
    def list(self) -> list[Carpark]: ...
    def list_by_location(self, location_id: int) -> list[Carpark]: ...
    def update(self, carpark: Carpark) -> Carpark: ...
    def delete(self, carpark_id: int) -> bool: ...


class BikeSharingRepository(Protocol):
    def add(self, point: BikeSharingPoint) -> BikeSharingPoint: ...
    def get_by_id(self, point_id: int) -> Optional[BikeSharingPoint]: ...
    def list(self) -> list[BikeSharingPoint]: ...
    def list_by_location(self, location_id: int) -> list[BikeSharingPoint]: ...
    def update(self, point: BikeSharingPoint) -> BikeSharingPoint: ...
    def delete(self, point_id: int) -> bool: ...
