"""
Repository interface for Report entity operations.
"""
from __future__ import annotations
from typing import Protocol, Optional
from app.models.report import Report, IncidentReport, TechnicalReport


class ReportRepository(Protocol):
    def add(self, report: Report) -> Report: ...
    def get_by_id(self, report_id: int) -> Optional[Report]: ...
    def list(self) -> list[Report]: ...
    def list_by_user(self, user_id: int) -> list[Report]: ...
    def list_incident_reports(self) -> list[IncidentReport]: ...
    def list_by_status(self, status: str) -> list[Report]: ...
    def update(self, report: Report) -> Report: ...
    def delete(self, report_id: int) -> bool: ...
