"""
Repository interface for Route entity operations.
"""
from __future__ import annotations
from typing import Protocol, Optional
from app.models.route import Route, UserSuggestedRoute


class RouteRepository(Protocol):
    def add(self, route: Route) -> Route: ...
    def get_by_id(self, route_id: int) -> Optional[Route]: ...
    def list(self) -> list[Route]: ...
    def list_by_user(self, user_id: int) -> list[UserSuggestedRoute]: ...
    def list_by_subtype(self, subtype: str) -> list[Route]: ...
    def update(self, route: Route) -> Route: ...
    def delete(self, route_id: int) -> bool: ...
