"""
Repository interface for Suggestion entity operations.
"""
from __future__ import annotations
from typing import Protocol, Optional
from app.models.suggestion import Suggestion


class SuggestionRepository(Protocol):
    def add(self, suggestion: Suggestion) -> Suggestion: ...
    def get_by_id(self, suggestion_id: int) -> Optional[Suggestion]: ...
    def list(self) -> list[Suggestion]: ...
    def list_by_status(self, status: str) -> list[Suggestion]: ...
    def update(self, suggestion: Suggestion) -> Suggestion: ...
    def delete(self, suggestion_id: int) -> bool: ...
