"""
Repository interface for SuggestionVote entity operations.
"""
from __future__ import annotations
from typing import Protocol, Optional
from app.models.suggestion_vote import SuggestionVote


class SuggestionVoteRepository(Protocol):
    def add(self, vote: SuggestionVote) -> SuggestionVote: ...
    def get_by_id(self, vote_id: int) -> Optional[SuggestionVote]: ...
    def list(self) -> list[SuggestionVote]: ...
    def list_by_route(self, route_id: int) -> list[SuggestionVote]: ...
    def list_by_user(self, user_id: int) -> list[SuggestionVote]: ...
    def get_user_vote_for_route(self, user_id: int, route_id: int) -> Optional[SuggestionVote]: ...
    def count_votes_for_route(self, route_id: int) -> dict[str, int]: ...  # Returns {"upvotes": n, "downvotes": m}
    def update(self, vote: SuggestionVote) -> SuggestionVote: ...
    def delete(self, vote_id: int) -> bool: ...
