"""
Repository port (interface) for TrafficAlert operations.
"""
from __future__ import annotations
from typing import Protocol, Optional
from app.models.traffic_alert import TrafficAlert


class TrafficAlertRepository(Protocol):
    def add(self, alert: TrafficAlert) -> TrafficAlert: ...
    def get_by_id(self, alert_id: int) -> Optional[TrafficAlert]: ...
    def get_by_alert_id(self, alert_id: str) -> Optional[TrafficAlert]: ...
    def list(self) -> list[TrafficAlert]: ...
    def list_active(self) -> list[TrafficAlert]: ...
    def list_by_status(self, status: str) -> list[TrafficAlert]: ...
    def update(self, alert: TrafficAlert) -> TrafficAlert: ...
    def delete(self, alert_id: int) -> bool: ...
