"""
Repository port (interface) for User operations.
"""
from __future__ import annotations
from typing import Protocol, Optional
from app.models.account import User, Account


class UserRepository(Protocol):
    def add(self, user: User) -> User: ...
    def get_by_id(self, user_id: int) -> Optional[User]: ...
    def get_by_email(self, email: str) -> Optional[User]: ...
    def get_by_username(self, username: str) -> Optional[User]: ...
    def list(self) -> list[User]: ...
    def update(self, user: User) -> User: ...
    def delete(self, user_id: int) -> bool: ...
    def add_saved_location(self, user_id: int, location_id: int) -> bool: ...
    def remove_saved_location(self, user_id: int, location_id: int) -> bool: ...
    def get_saved_locations(self, user_id: int) -> list[int]: ...
